remote_theme: daviddarnes/alembic@master
plugins:
- jekyll-remote-theme

title: Ball_Recognizer
description: An image classification API that classifies 12 different Balls which are used in different games around the world.
author:
  name: Md.Gias Kamal